Repository quaternionmedia/midiphonor, pull requests merged in 2022-07, with the labels that each got.

#7 Add auto-release milestones from published qm/milestones
  .github/workflows/auto-release.yml
Labels: enhancement :heavy_plus_sign:, CD :building_construction:, maintenance :wrench:

#8 Adds release template
  .github/release.yml
Labels: documentation :scroll:, CD :building_construction:

#9 Dev
  .github/workflows/website_deploy.yml
  .gitignore
  .prettierrc
  midiphonor
  package.json
  src/components/bpm.ts
  src/components/clock.ts
  src/components/components.ts
  src/components/note.ts
  src/components/transport.css
  src/components/transport.ts
  src/index.ts
  src/state.ts
  src/types.ts
  src/utils.ts
Labels: documentation :scroll:, enhancement :heavy_plus_sign:, CD :building_construction:

#4 Menu
  components.md
  src/components/bpm.ts
  src/components/clock.ts
  src/components/menu.ts
  src/components/transport.ts
  src/index.ts
  src/utils.ts
Labels: enhancement :heavy_plus_sign:

#10 Update dependencies to latest versions
  package.json
Labels: maintenance :wrench:

#5 State
  components.md
  midiphonor
  package.json
  src/actions.ts
  src/components/bpm.ts
  src/components/clock.ts
  src/components/components.ts
  src/components/menu.ts
  src/components/transport.css
  src/components/transport.ts
  src/index.ts
  src/state.ts
  src/types.ts
Labels: enhancement :heavy_plus_sign:, breaking :broken_heart:

#11 Typescript comments
  src/components/components.ts
  src/components/transport.ts
Labels: documentation :scroll:

#12 Observable state
  src/index.ts
  src/state.ts
  src/syntax.css
  src/utils.ts
Labels: enhancement :heavy_plus_sign:

#15 Migrate to new components folder structure
  src/components/generators/note.ts
  src/components/state.ts
  src/components/syntax.css
  src/components/transports/bpm.ts
  src/components/transports/clock.ts
  src/components/transports/transport.css
  src/components/transports/transport.ts
  src/index.ts
  src/state.ts
  src/utils/streams.ts
Labels: documentation :scroll:, maintenance :wrench:

#21 Nexus UI note
  package.json
  src/components/components.ts
  src/components/generators/note.ts
  src/components/transports/bpm.ts
  src/components/transports/transport.css
  src/index.ts
  src/utils/maths.ts
  src/utils/music.ts
Labels: documentation :scroll:, enhancement :heavy_plus_sign:

#22 Added default synth component
  src/components/generators/note.ts
  src/components/generators/synth.ts
  src/index.ts
Labels: enhancement :heavy_plus_sign:, maintenance :wrench:

#23 split MidiPortSelect into own component
  src/components/menu.ts
Labels: maintenance :wrench:

#24 Visualization component with Meter, Oscilloscope, Spectrogram
  src/components/visualizers/meter.ts
  src/components/visualizers/oscilloscope.ts
  src/components/visualizers/spectrogram.ts
  src/components/visualizers/visualizer.ts
  src/index.ts
Labels: enhancement :heavy_plus_sign:

#25 Sequencer component :1234:
  src/components/generators/note.ts
  src/components/generators/sequencer.css
  src/components/generators/sequencer.ts
  src/index.ts
Labels: enhancement :heavy_plus_sign:

#27 Create Cells 🔬
  src/actions.ts
  src/components/menu.ts
  src/components/state.ts
  src/components/transports/clock.ts
  src/components/transports/transport.ts
  src/index.ts
  src/state.ts
  src/types.ts
Labels: enhancement :heavy_plus_sign:, breaking :broken_heart:

#28 Observable streams 🚰
  package.json
  src/actions.ts
  src/components/state.ts
  src/components/tracer.ts
  src/components/transports/clock.ts
  src/components/transports/transport.css
  src/components/transports/transport.ts
  src/state.ts
  src/types.ts
Labels: enhancement :heavy_plus_sign:

#30 💓 Bpm component - cell structure
  src/components/components.ts
  src/components/transports/bpm.ts
  src/index.ts
  src/utils/streams.ts
Labels: enhancement :heavy_plus_sign:

#31 Add `./midiphonor cmd` for quick bash entry to node container
  midiphonor
Labels: enhancement :heavy_plus_sign:

#32 Cell types
  src/components/generators/synth.ts
  src/index.ts
  src/utils/maths.ts
  src/utils/music.ts
Labels: documentation :scroll:
